# Generated by Django 5.1.3 on 2024-11-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image_url", models.URLField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Music", "Music"),
                            ("Video", "Video"),
                            ("Art", "Art"),
                            ("Code", "Code"),
                        ],
                        max_length=50,
                    ),
                ),
                ("pricing", models.CharField(max_length=50)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
