# Generated by Django 5.1.3 on 2024-11-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tool",
            name="image_url",
        ),
        migrations.AddField(
            model_name="tool",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tool_images/"),
        ),
    ]
