# Generated by Django 5.1.3 on 2024-11-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0003_category_alter_tool_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="category",
            field=models.CharField(
                choices=[
                    ("Music", "Music"),
                    ("Video", "Video"),
                    ("Art", "Art"),
                    ("Code", "Code"),
                    ("Docs", "Docs"),
                    ("Study", "Study"),
                    ("Career", "Career"),
                    ("Present", "Present"),
                    ("Marketing", "Marketing"),
                    ("Finance", "Finance"),
                    ("Analytics", "Analytics"),
                    ("Translate", "Translate"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
